apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-ecommerce-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hrishikesh2901/Django-Ecommerce.git' #
    targetRevision: HEAD
    path: django-chart #
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true